const express = require('express')
const router = express.Router({ mergeParams: true })
const { isLoggedIn } = require('../middleware')
const controller = require('../controllers/note')
const catchAsync = require('../utils/catchAsync')

router.use(isLoggedIn)
router.post('/:noteId/delete/:id', catchAsync(controller.delete))
router.post('/:noteId/edit/:id', catchAsync(controller.edit))
router.post('/:noteId/archive/:id', catchAsync(controller.archive))
router.post('/:noteId/archive/', catchAsync(controller.archive))
router.post('/:noteId/flag/:id', catchAsync(controller.flag))
router.post('/:noteId/flag/', catchAsync(controller.flag))
router.post('/:noteId/restore/:id', catchAsync(controller.restore))
router.post('/:noteId/restore/', catchAsync(controller.restore))
router.post('/:noteId/complete/:id', catchAsync(controller.finish))
router.post('/:noteId/complete/', catchAsync(controller.finish))
router.post('/:noteId/delete/', catchAsync(controller.delete))
router.post('/:noteId/edit/', catchAsync(controller.edit))
router.post('/:entryId', catchAsync(controller.create))

module.exports = router;